# This is a basic workflow to help you get started with Actions

name: Example Two

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'composite/*'
      - 'workdir/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  stage_one:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #Uses the composite action in this repo
      - uses: ./.github/actions/example_action
        with:
          input_one: "This is some text"
      # Uses our own composite action from another repo, has to be public or you need to set up some PAT authentication etc.
      - uses: mbids/composite-actions@v3

      #insert a step that uses an internal repository/private repository by checking out that repo 
      - uses: actions/checkout@v2
        with:
          repository: mbids/private-composite-action
          token: ${{ secrets.GH_PAT }} 
          path: private-composite-action
      - uses: ./private-composite-action
