name: Example three

on:
  workflow_dispatch:


jobs:
  stage1:
    uses: ./.github/workflows/shared_example_one.yml
    with:
      input_one: 'This is input variable one for a reusable workflow'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      

          
