name: Example four
on:
  workflow_dispatch:

jobs:
  stage1:
    runs-on: ubuntu-latest
    container:
        image: node:18
        env:
          NODE_ENV: development
        ports:
          - 80
        volumes:
          - /tmp:/tmp

    steps:
      - name: "Illustrate node version"
        run: |
          npm --version
